#- name: Check if Job exists or not - {{item.dir}}/{{item.name}}
#  ansible.builtin.shell: java -jar /opt/jenkins-cli.jar -auth admin:{{jenkins_password}} -s http://100.27.244.164:8080 -webSocket get-job {{item.dir}}/{{item.name}}
#  register: out
#  ignore_errors: yes

#- name: Create Config file - {{item.dir}}/{{item.name}}
#  ansible.builtin.template:
#    src: m-job.xml
#    dest: /tmp/m-job.xml
#  vars:
#    unique_key: lookup('community.general.random_string', special=false, upper=false, length=12)
#  when: out.rc == 3

#- name: Create Job - {{item.dir}}/{{item.name}}
#  community.general.jenkins_job:
#    config: "{{ lookup('file', '/tmp/m-job.xml') }}"
#    name: "{{item.dir}}/{{item.name}}"
#    url: http://100.27.244.164:8080
#    user: admin
#    password: "{{jenkins_password}}"
#  when: out.rc == 3


- name: Create Folder
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    url: http://172.31.7.18:8080
    user: admin
    password: "{{jenkins_password}}"
  loop: "{{ folders }}"

- name: Create Pipeline Jobs
  ansible.builtin.include_tasks: pipeline.yml
  vars:
    COMPONENT: "{{item}}"
    #DIR: "{{item.dir}}"
  loop: "{{ pipeline_jobs }}"